[package]
name = "resh"
version = "0.2.0"
authors = ["Koen Wilde <koen@chillheid.nl>"]
description = "A restricted shell that only allows execution of previously defined aliases"
edition = "2018"

homepage = "https://github.com/koenw/resh"
repository = "https://github.com/koenw/resh"

readme = "README.md"
license = "MIT"
keywords = ["shell", "ssh", "restricted", "nrpe"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
clap = { version = "4", features = ["cargo"] }
